apiVersion: v1
kind: ReplicationController
metadata:
  name: mern-node-rc
spec:
  replicas: 3
  selector:
    app: mern-node
  template:
    metadata:
      name: mern-node-pod
      labels:
        app: mern-node
    spec:
      containers:
      - name: mern-node
        image: gcr.io/onthermern/mern_client:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000